### ISSUE TITLE
argocd with this plugin ignores namespace definitions

### ISSUE THREAD

**Issue by Nexus2k** [travisghansen/argo-cd-helmfile#14]
We have multiple helmfile.d based deployments that deploy different charts in different namespaces.
E.g. content of 10-postgres.yml
```
...
  - name: postgresql
    namespace: namespace-1
    chart: bitnami/postgresql
    version: v11.1.4
  - name: postgresql
    namespace: namespace-2
    chart: bitnami/postgresql
    version: v11.1.4
```

When not defining a destination namespace argocd creates configmaps, serviceaccounts and other things w/o namespace metadata and therefore in the wrong namespace. Using helmfile -f ./helmfile.d sync does respect the namespace stanza and deploys the k8s objects in the correct namespaces.

**Comment by travisghansen** [comment]
The namespace should be the namespace of the app in argocd. It’s not recommended to set the namespace in your helmfiles.

**Comment by Nexus2k** [comment]
Not recommend != not supported. I'll rather not use argocd and your plugin then. Thanks for getting back to me.

**Comment by travisghansen** [comment]
I’m happy to look into it but I’m not sure what you want the plugin to do. You will be limited by the limitations of both argocd and helmfile.

This plugin itself does nothing more than run helmfile template and hands the resultant files/output to argocd. The script doesn’t manipulate the contents of the rendered files at all.

**Comment by Nexus2k** [comment]
Let's say we have a complicated helm deployment called base-services which deploys different helm charts in different namespaces in one go. E.g. 01-kube-prometheus.yaml in namespace: monitoring / nginx-controller in namespace: default / hairpin-proxy in namespace: hairpin-proxy

**Comment by travisghansen** [comment]
Have you been able to achieve that generally with argocd? I don’t think that’s a thing with argocd generally, and certainly doesn’t follow any best practices.

When argocd applies the yaml behind the scenes it explicitly calls out -n <ns> to match the namespace of the app. Using an app in 1 namespace to deploy assets to another namespace would be highly irregular (if not impossible) to my knowledge.

If you do create separate apps for each ns you can still use your centralized hemfile repo, but you would add a label on the releases instead of using the namespace property and then filter with labels.
